from api.settings import env

# BASE
MICROSERVICE_ALL_HOST = env.str("MICROSERVICE_ALL_HOST", default="")  # localhost

# Admin
MICROSERVICE_ADMIN_HOST = env.str("MICROSERVICE_ADMIN_HOST", default=MICROSERVICE_ALL_HOST or "admin")
MICROSERVICE_ADMIN_PORT = env.int("MICROSERVICE_ADMIN_HOST", default=8010)

# Auth
MICROSERVICE_AUTH_HOST = env.str("MICROSERVICE_AUTH_HOST", default=MICROSERVICE_ALL_HOST or "auth")
MICROSERVICE_AUTH_PORT = env.int("MICROSERVICE_AUTH_HOST", default=8011)

# Teams
MICROSERVICE_TEAMS_HOST = env.str("MICROSERVICE_TEAMS_HOST", default=MICROSERVICE_ALL_HOST or "teams")
MICROSERVICE_TEAMS_PORT = env.int("MICROSERVICE_TEAMS_HOST", default=8012)

# Users
MICROSERVICE_USERS_HOST = env.str("MICROSERVICE_USERS_HOST", default=MICROSERVICE_ALL_HOST or "users")
MICROSERVICE_USERS_PORT = env.int("MICROSERVICE_USERS_HOST", default=8013)

# Conversations
MICROSERVICE_CONVERSATIONS_HOST = env.str(
    "MICROSERVICE_CONVERSATIONS_HOST", default=(MICROSERVICE_ALL_HOST or "conversations")
)
MICROSERVICE_CONVERSATIONS_PORT = env.int("MICROSERVICE_CONVERSATIONS_HOST", default=8014)
