# Generated by Django 5.0.2 on 2024-03-30 09:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAvatar",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("creator_id", models.CharField(default="", max_length=20)),
                ("updater_id", models.CharField(default="", max_length=20)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("team_id", models.CharField(max_length=50)),
                ("avatar_hash", models.CharField(default="", max_length=255)),
                ("temp_hash", models.CharField(default="", max_length=255)),
                ("metadata", models.JSONField(default=dict, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="avatar", to="users.user"
                    ),
                ),
            ],
            options={
                "db_table": "user_avatars",
                "ordering": ["-created"],
            },
        ),
    ]
